// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  cloudWatchDomain: 'https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=',
  ecsUtilitiesUrl: 'https://ecs-utilities.preprod.amer.amway.net',
  kafkaUtilitiesUrl: 'http://kafka-rest-proxy-preprod.preprod.amer.amway.net',
  systemActivitiesUrl: 'https://system-activities.preprod.amer.amway.net',
  applyChanges: false,
  searchForceUrl: 'http://search-force.preprod.amer.amway.net',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  oktaConfig: {
    issuer: 'https://dev-587527.oktapreview.com/oauth2/default',
    clientId: '0oainf6sqdsP8vwbq0h7',
    redirectUri: 'http://localhost:4200/implicit/callback'
    // redirectUri: 'http://infra.preprod.amer.amway.net/implicit/callback',
  }
};
