AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Redirect to SSL, Custom DomainName, Edge Gzip, Angular Redirects, S3 origin bucket
Parameters:
 Branch:
  Description: Git branch
  Type: String
  Default: master
 Environment:
  Description: Environment
  Type: String
  Default: preprod
 AcmCertificateArn:
  Description: The ARN of a certificate from AWS Certificate Manager (ACM)
  Type: String
  Default: arn:aws:iam::655648606120:server-certificate/preprod.amer.amway.net
 CloudFrontCname:
  Description: Custom domain name to use (foo.yourdomain.com).
  Type: String
  Default: infra.preprod.amer.amway.net
  AllowedPattern : (([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.){2,}([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]){2,}
  ConstraintDescription : Must be a valid DNS zone name WITHOUT trailing period
Resources:
 AppBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: 'Delete'
  Properties:
   BucketName: !Sub infra-manager-${Environment}
   AccessControl: PublicRead
   WebsiteConfiguration:
    IndexDocument: index.html
   VersioningConfiguration:
    Status: Enabled
 AppBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
   PolicyDocument:
    Id: WebAppBucketPolicy
    Version: 2012-10-17
    Statement:
      Sid: PublicReadForGetBucketObjects
      Effect: Allow
      Principal: '*'
      Action: 's3:GetObject'
      Resource: !Sub
       - arn:aws:s3:::${AppBucket}/*
       - { AppBucket: !Ref AppBucket }
   Bucket: !Ref AppBucket
 OriginAccessIdentity:
  Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  Properties:
   CloudFrontOriginAccessIdentityConfig:
    Comment: Access identity between CloudFront and S3 bucket
 CloudFront:
  Type: AWS::CloudFront::Distribution
  DependsOn: AppBucket
  Properties:
   DistributionConfig:
    Enabled: true
    IPV6Enabled: true
    HttpVersion: http2
    DefaultRootObject: index.html
    Comment: !Join [ '', [!Ref 'AWS::StackName', ' Angular CloudFront']]
    Aliases:
     - !Sub ${CloudFrontCname}
    Origins:
     - DomainName: !Sub ${AppBucket}.s3.amazonaws.com
       Id: myS3Origin
       S3OriginConfig:
         OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
    DefaultCacheBehavior:
     AllowedMethods: ["GET", "HEAD", "OPTIONS"]
     CachedMethods: ["GET", "HEAD", "OPTIONS"]
     ForwardedValues:
      Headers:
      - Access-Control-Request-Headers
      - Access-Control-Request-Method
      - Origin
      - Authorization
      QueryString: false
      Cookies:
       Forward: none
     TargetOriginId: myS3Origin
     ViewerProtocolPolicy: redirect-to-https
     Compress: true
     DefaultTTL: 0
    CustomErrorResponses:
    - ErrorCode: 404
      ResponsePagePath: /index.html
      ResponseCode: 200
      ErrorCachingMinTTL: 300
    - ErrorCode: 400
      ErrorCachingMinTTL: 0
    - ErrorCode: 403
      ErrorCachingMinTTL: 1
    - ErrorCode: 500
      ErrorCachingMinTTL: 5
Outputs:
 Version:
  Description: Infrastructure Manager (Preproduction Environment)
  Value: 1.0.0
 CloudFront:
  Description: CloudFront ID
  Value: !Ref CloudFront
